### ISSUE TITLE
Code visible in browser bar

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#22]
when entering the 'code'  its hidden 

but as it is passed as URL two things happen

- the URL: voucher?code=1234&type=480,0,,, is shown

Result: the code is visible which can become a potential issue

2. When reloading the page: the system is creating multiple vouchers (when reloading multiple times)

3. System is not aware that there are more options for creating a voucher (week/year), than you need to press the logo again (which can be intentionally)

**Comment by glenndehaan** [comment]
This is all intended

**Comment by glenndehaan** [comment]
Hi,

Due to the changes required to implement #29 I have resolved both of these issues.

- Url query parameters a not used anymore within the application
- The flow of pages has been changed, there is now a dedicated login page before you can create vouchers.
- Due to this flow change: You cannot accidentally create vouchers by refeshing the page
- After creating a voucher you will land on the voucher page itself now. This allows you to change the type of voucher you can create for the next creation flow.

Also good to know: #29 introduces a simple Voucher Overview:
![localhost_3000_vouchers](https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/99fc3147-f795-4cb0-a44c-04a9e1012da1)

Kind regards,
Glenn de Haan
