### ISSUE TITLE
Question for enhancements

### ISSUE THREAD

**Issue by tomcatcw1980** [glenndehaan/unifi-voucher-site#29]
Hello Glenn, 

I would like to emphasize once again that I think the project is great. Since I'm not a programmer, I can't judge what kind of effort is behind the two points. I have the pure user glasses on. :-)

Here are two enhancements. Do you think that would be feasible?

a) Display of existing vouchers that are still valid
b) to be more flexible, the points such as time and multi-use, single-use, upload and download rates could be designed as input fields

Many thanks for your assessment.

Best regards
Christian

**Comment by glenndehaan** [comment]
Hi Christian,

I understand you suggestions, but the initial idea of the portal comes from my own work.
Here I wanted to have a simple way for non-system admins to request vouchers for guests without opening those people up to the whole unifi controller.

This is why the voucher properties are set from the backend and not the frontend. I wanted control over the values that people could use.

Your first question is one I could understand is useful to just see if there are still vouchers in use.

I will try to see if I can come up with something simple for this. Won't promise it will be there soon, due to some other projects I have going on.

Kind regards,
Glenn de Haan

**Comment by glenndehaan** [comment]
Hi Christian,

Good news I just pushed an update of the application that now allows you to view available vouchers within the app:

![localhost_3000_vouchers](https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/e6f679c2-9b89-44ab-8399-7e17a0aad559)

Will close this issue for now.

Kind regards,
Glenn de Haan

**Comment by tomcatcw1980** [comment]
Hi Glenn, thank you very much for your help. Looking forward for further enhancements and news from your project. 

Greetings. 

Christian

**Comment by glenndehaan** [comment]
Goodmorning Christian,

I have some great news. After the redesign of the entire app it's now finally possible to create 'Custom' voucher types within the UI as you suggested. This feature is available from version 2.4.0 that has just been released:

<img width="1440" alt="afbeelding" src="https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/e836f56b-26a9-4854-b81a-390703a0be1f">

**Comment by tomcatcw1980** [comment]
Hi Glenn,

That's fantastic. I'll try it out right away. Thank you very much.

Greetings Christian
