### ISSUE TITLE
Unhealthy Status

### ISSUE THREAD

**Issue by tomcatcw1980** [glenndehaan/unifi-voucher-site#32]
Hi Glenn,

the app works right after start. But then becomes unhealthy status after some minutes and must be restartet.

Can you check whats going on.

Thank you very much.

Greetings
Christian

**Comment by glenndehaan** [comment]
Hi Christian,

Can you describe what you mean with unhealthy.
I have the latest version running I don't see any issues.

Maybe you can send the log output and/or some screenshots?

Kind regards,
Glenn

**Comment by tomcatcw1980** [comment]
Hi Glenn,

please find attached some screenshots.

In the logs of Portainer aren't any errors.

Greetings
![Screenshot 2024-04-15 093640](https://github.com/glenndehaan/unifi-voucher-site/assets/58996205/01206fc0-c28c-499e-ab55-d2004b0458c6)
![Screenshot 2024-04-15 093745](https://github.com/glenndehaan/unifi-voucher-site/assets/58996205/762a1df7-d3de-4088-88a9-19165174af0f)

**Comment by glenndehaan** [comment]
This is pretty weird. It almost seems like you have an internal network issue going on.
And the reason that I think that is the fact that the healthcheck is basically a static page that always resolves no matter if the app has an issue. So the unhealty state would lead me to believe something is blocking network connectivity inside the container.

Could you try to export a complete log from start to finish. Because i'm curious if the UniFi request fails due to an authentication error. Or it is unable to even connect to the host.

**Comment by glenndehaan** [comment]
Maybe we could do a screenshare session in the evening if you have time? I would be available from 18:00 CEST

**Comment by glenndehaan** [comment]
So I have an update from my side. I think I have figured out why the healthcheck is failing on your side. It seems like it tries to connect over IPv6 instaid of IPv4. I have a fix for that ready and hope to be able to release this within the next hour or so. I'm currently also working on a revamp for the UniFi login. However I would still need your complete log to verify that this lines up with what I think is going wrong.

**Comment by tomcatcw1980** [comment]
Hi Glenn, sounds good. Can you tell me how to extract the logs?

Greetings

**Comment by glenndehaan** [comment]
If you are using portainer then it's just a matter of increasing the 'Lines' variable until the export starts with the logo:
<img width="922" alt="afbeelding" src="https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/61f61e0e-67e9-4816-97a9-9abaa021164b">
<img width="890" alt="afbeelding" src="https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/609c666a-353c-42bd-8cc9-21859f38e12f">

**Comment by glenndehaan** [comment]
Hi Christian,

A new version is available for you to try

**Comment by glenndehaan** [comment]
Hi Christian,

Great to hear. Looking at the new log you provided it also seems the errors are fixed with the new re-authentication method.
It seems the token your UniFi controller supplies is even shorter then the 1 hour my controller supplies.
So I think this issue is solved for now. If you still see a problem please let me know.

Kind regards,
Glenn de Haan
